spring:
    profiles:
        active: 
        - dev
--- 
spring:
    profiles: dev
    application:
        name: nayunspringcloud-config-atguigu-dev
--- 
spring:
    profiles: test
    application:
        name: nayunspringcloud-config-atguigu-test